    { "abuse"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "accuse"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "ack"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "afk"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "agree"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "apologize"  , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "applaud"    , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "banzai"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "bark"       , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "bearhug"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "beckon"     , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "beg"        , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "belch"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "bite"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "bleed"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "blush"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "boggle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "bonk"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "booger"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "bounce"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "bow"        , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "brb"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "burp"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "cackle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "cheer"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "chuckle"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "clap"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "comb"       , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "comfort"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "complain"   , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "confuse"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "contemplate", POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "cookie"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "cough"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "cringe"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "cry"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "cuddle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "curse"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "curtsey"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "dance"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "daydream"   , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "dead"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "demand"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "drool"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "duck"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "duh"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "eek"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "egg"        , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "embrace"    , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "faint"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "fart"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "flare"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "flex"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "flip"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "flirt"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "fondle"     , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "forehead"   , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "french"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "frown"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "fume"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "gag"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "gasp"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "gawk"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "giggle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "gimme"      , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "glare"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "goose"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "greet"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "grin"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "groan"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "grope"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "grovel"     , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "growl"      , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "grumble"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "gulp"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "harrass"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "headbutt"   , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "highfive"   , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "holdbreathe", POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "hop"        , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "howl"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "hug"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "huh"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "hum"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "idiot"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "innocent"   , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "inspire"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "jig"        , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "jump"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "kiss"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "kisshand"   , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "kneel"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "lag"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "laugh"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "leer"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "level"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "lick"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "lol"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "loser"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "love"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "massage"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "melt"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "moan"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "mock"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "moon"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "mosh"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "muh"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "mumble"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "mutter"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "nibble"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "night"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "nitpick"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "nod"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "noogie"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "nudge"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "nuzzle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "ooops"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "ouch"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "pace"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "panic"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "pant"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "pat"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "patback"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "peer"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "pet"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "piddle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "pillow"     , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "pinch"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "point"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "poke"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "ponder"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "pounce"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "pout"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "prance"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "protect"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "puke"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "pull"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "puzzle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "raise"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "relax"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "roll"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "ruffle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "salute"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "scoff"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "scratch"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "scream"     , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "seduce"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "shake"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "shh"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "shiver"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "shrug"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "shudder"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "sigh"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "sing"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "slam"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "slap"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "smile"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "smirk"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "smoke"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "smooch"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "smother"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "snap"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "snarl"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "sneeze"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "snicker"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "sniff"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "snore"      , POS_SLEEPING, do_action, 0, 0, AFF_HIDE },
    { "snort"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "snowball"   , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "snuggle"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "sob"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "spank"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "spit"       , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "squeeze"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "stagger"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "stare"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "stomp"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "strangle"   , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "stroke"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "strut"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "stump"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "sulk"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "swear"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "sweat"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "tackle"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "tango"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "tap"        , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "taunt"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "tease"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "thank"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "think"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "thwap"      , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "tickle"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "tongue"     , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "triumph"    , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "twiddle"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "wave"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "wetwilly"   , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "whine"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "whistle"    , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "wiggle"     , POS_STANDING, do_action, 0, 0, AFF_HIDE },
    { "wink"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "worship"    , POS_SITTING , do_action, 0, 0, AFF_HIDE },
    { "yawn"       , POS_RESTING , do_action, 0, 0, AFF_HIDE },
    { "yodel"      , POS_RESTING , do_action, 0, 0, AFF_HIDE },
